### ISSUE TITLE
Mixed with REI causes looping Error in logs, 

### ISSUE THREAD

**Issue by Merith-TK** [Tacodude7729/Totemic-Overhaul-Fabric#12]
THis can create a log file of upwards to 10gb in under a few minutes.

**Comment by Tacodude7729** [comment]
Will be looking into fixing this but I wouldn't be supported if it's on REIs side given it's still in alpha for 1.17. If it is I'll submit an issue there

**Comment by Tacodude7729** [comment]
Fixed in eb046c3572b22625dc3b4c9d344ac51d92c29cdd as of 1.1.7
