### ISSUE TITLE
REI Won't Display

### ISSUE THREAD

**Issue by SaltSouls** [Tacodude7729/Totemic-Overhaul-Fabric#13]
When totemic overhaul is enabled, REI fails to actually display. No amount of messing with the keybindings fixes it. It also breaks the recipe book as no recipes from there will display either. I know it is this mod, as the instant I disable it everything works again.

Log:
- [uhoh.json](https://github.com/Tacodude7729/Totemic-Overhaul-Fabric/files/6762883/latest.log)

Crash Report:
- [totemic_collision.toml](https://github.com/Tacodude7729/Totemic-Overhaul-Fabric/files/6762871/crash-2021-07-05_01.31.27-client.txt)

**Comment by Tacodude7729** [comment]
See #12 and https://github.com/shedaniel/RoughlyEnoughItems/issues/579

**Comment by Tacodude7729** [comment]
Fixed in eb046c3572b22625dc3b4c9d344ac51d92c29cdd as of 1.1.7
